# Python package
# Create and test a Python package on multiple Python versions.
trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# 🔧 Install system dependencies required by textract and others
- script: |
    sudo apt-get update
    sudo apt-get install -y \
      poppler-utils \
      tesseract-ocr \
      libxml2-dev \
      libxslt1-dev \
      antiword \
      unrtf \
      python3-dev \
      build-essential
  displayName: 'Install system dependencies'

# 📦 Install Python dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

# 🧪 Run tests
- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'Run tests with pytest'
